# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
import numpy as np

arr = np.array([1, 3, 7, 9, 15, 20])
target = 8

idx = (np.abs(arr - target)).argmin()

nearest_value = arr[idx]

print("Nearest value to", target, "is", nearest_value)


Nearest value to 8 is 7


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [2]:
import numpy as np

A = np.array([[1, 2, 3]])  
B = np.array([[4], [5], [6]]) 

# Create an iterator
it = np.nditer([A, B, None]) 

for x, y, res in it:
    res[...] = x + y  


result = it.operands[2]

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆)

In [3]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name  
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "Unnamed") 

arr = NamedArray([1, 2, 3, 4], name="MyArray")

print(arr)          
print(arr.name)     


[1 2 3 4]
MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [4]:
import numpy as np

# Given vector
vector = np.array([0, 1, 2, 3, 4, 5])

# Index array (indices to increment)
indices = np.array([0, 1, 1, 2, 3, 3, 3])

# Use np.add.at to increment values at the specified indices
np.add.at(vector, indices, 1)

print(vector)


[1 3 3 6 4 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [5]:
import numpy as np

X = np.array([1, 2, 3, 4, 5])  
I = np.array([0, 1, 2, 1, 3])  


F = np.zeros(5, dtype=int) 

np.add.at(F, I, X)

print(F)


[1 6 3 5 0]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [6]:
import numpy as np

# Create a random (w, h, 3) image with dtype=ubyte
w, h = 100, 100  # Example image size
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)  # Random RGB image

# Reshape to a 2D array where each row is a color (R, G, B)
reshaped_image = image.reshape(-1, 3)

# Find unique rows (unique colors) and count them
unique_colors = np.unique(reshaped_image, axis=0)

# Number of unique colors
num_unique_colors = len(unique_colors)

print(f"Number of unique colors: {num_unique_colors}")


Number of unique colors: 9997


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [7]:
import numpy as np

array = np.random.rand(2, 3, 4, 5)

result = np.sum(array, axis=(-2, -1))

print("Original shape:", array.shape)
print("New shape after summing over last two axes:", result.shape)


Original shape: (2, 3, 4, 5)
New shape after summing over last two axes: (2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [8]:
import numpy as np

D = np.array([10, 20, 30, 40, 50, 60])  
S = np.array([0, 1, 0, 1, 2, 2])  

sum_per_subset = np.bincount(S, weights=D)

count_per_subset = np.bincount(S)

mean_per_subset = sum_per_subset / count_per_subset

print("Means of subsets:", mean_per_subset)


Means of subsets: [20. 30. 55.]


#### 69. How to get the diagonal of a dot product? (★★★)

In [9]:
import numpy as np

# Create two random matrices
A = np.random.rand(4, 4)
B = np.random.rand(4, 4)

# Compute only the diagonal of the dot product (A @ B)
diagonal = np.einsum("ij,ji->i", A, B.T)

print("Diagonal of dot product:", diagonal)


Diagonal of dot product: [1.4746518  0.4683698  0.64752195 1.37005938]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [10]:
import numpy as np

# Original vector
vector = np.array([1, 2, 3, 4, 5])

new_vector = np.zeros(len(vector) * 4, dtype=vector.dtype)

new_vector[::4] = vector

print(new_vector)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 72. How to swap two rows of an array? (★★★)

In [11]:
import numpy as np

# Create a sample 2D array
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Swap row 0 and row 2
A[[0, 2]] = A[[2, 0]]

print(A)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [12]:
import numpy as np

triangles = np.random.randint(0, 20, (10, 3))  
edges = np.sort(np.array([
    [triangles[:, 0], triangles[:, 1]],
    [triangles[:, 1], triangles[:, 2]],
    [triangles[:, 2], triangles[:, 0]]
]).T, axis=2)  
edges = edges.reshape(-1, 2)

unique_edges = np.unique(edges, axis=0)

print("Unique edges:")
print(unique_edges)


Unique edges:
[[ 0  4]
 [ 0  7]
 [ 1  7]
 [ 4 12]
 [ 4 13]
 [ 4 17]
 [ 6  7]
 [ 6 15]
 [ 6 16]
 [ 7  1]
 [ 7  7]
 [ 7  8]
 [ 7 17]
 [ 8  6]
 [ 8 18]
 [ 9 18]
 [12 14]
 [13 15]
 [14  4]
 [15  4]
 [15  6]
 [15 15]
 [16 19]
 [17  0]
 [18  7]
 [18 19]
 [19  6]
 [19  9]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [13]:
import numpy as np


C = np.array([3, 0, 2, 1])  
A = np.repeat(np.arange(len(C)), C)

print("Reconstructed A:", A)
print("Check bincount:", np.bincount(A))  


Reconstructed A: [0 0 0 2 2 3]
Check bincount: [3 0 2 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [14]:
import numpy as np

def moving_average(arr, window_size):
    return np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

result = moving_average(arr, 3)

print("Sliding window averages:", result)


Sliding window averages: [2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [15]:
import numpy as np

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

window_size = 3
result = np.lib.stride_tricks.sliding_window_view(Z, window_size)

print(result)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [16]:
import numpy as np

bool_arr = np.array([True, False, True, True, False])

bool_arr[:] = ~bool_arr  

print(bool_arr)  


[False  True False False  True]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [19]:
import numpy as np

# Define sets of points
P0 = np.array([[0, 0], [1, 1], [2, 2]])  
P1 = np.array([[1, 0], [2, 2], [3, 3]])  
p = np.array([0, 1])  

# Compute the distances using the formula
line_vec = P1 - P0  
point_vec = P0 - p  

# Compute cross product of the 2D vectors (determinant)
cross_product = np.abs(line_vec[:, 0] * point_vec[:, 1] - line_vec[:, 1] * point_vec[:, 0])

# Compute line lengths
line_length = np.linalg.norm(line_vec, axis=1)

# Compute distances
distances = cross_product / line_length

print(distances)


[1.         0.70710678 0.70710678]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [20]:
import numpy as np


P0 = np.array([[0, 0], [1, 1], [2, 2]]) 
P1 = np.array([[1, 0], [2, 2], [3, 3]])  
P = np.array([[0, 1], [1, 0], [2, 3]])  

line_vec = P1 - P0  

line_length = np.linalg.norm(line_vec, axis=1)  


distances = np.zeros((len(P), len(P0))) 

for j in range(len(P)):  
    point_vec = P0 - P[j] 
    cross_product = np.abs(line_vec[:, 0] * point_vec[:, 1] - line_vec[:, 1] * point_vec[:, 0])  # Shape (N,)
    distances[j] = cross_product / line_length

# Define sets of points
P0 = np.array([[0, 0], [1, 1], [2, 2]]) 
P1 = np.array([[1, 0], [2, 2], [3, 3]]) 
P = np.array([[0, 1], [1, 0], [2, 3]])   

print(distances)


[[1.         0.70710678 0.70710678]
 [0.         0.70710678 0.70710678]
 [3.         0.70710678 0.70710678]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [22]:
import numpy as np

def extract_subarray(arr, center, shape, fill=0):
    rows, cols = shape
    cx, cy = center 
    

    start_x, end_x = cx - rows // 2, cx + (rows + 1) // 2
    start_y, end_y = cy - cols // 2, cy + (cols + 1) // 2


    subarray = np.full((rows, cols), fill, dtype=arr.dtype)


    x_min = max(start_x, 0)
    x_max = min(end_x, arr.shape[0])
    y_min = max(start_y, 0)
    y_max = min(end_y, arr.shape[1])

    sx_min, sx_max = x_min - start_x, x_max - start_x
    sy_min, sy_max = y_min - start_y, y_max - start_y


    subarray[sx_min:sx_max, sy_min:sy_max] = arr[x_min:x_max, y_min:y_max]

    return subarray


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [23]:
import numpy as np

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window_size = 4 

from numpy.lib.stride_tricks import sliding_window_view
R = sliding_window_view(Z, window_size)

print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [24]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank = np.linalg.matrix_rank(A)

print("Matrix Rank:", rank)


Matrix Rank: 2


#### 83. How to find the most frequent value in an array?

In [25]:
import numpy as np

arr = np.array([1, 3, 2, 3, 4, 3, 5, 2, 1, 3])

most_frequent = np.bincount(arr).argmax()

print("Most frequent value:", most_frequent)


Most frequent value: 3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [26]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# Create a random 10x10 matrix
matrix = np.random.randint(0, 100, (10, 10))

# Extract contiguous 3x3 blocks
blocks = sliding_window_view(matrix, (3, 3))

print("Shape of extracted blocks:", blocks.shape)  # (8, 8, 3, 3)
print("First 3x3 block:\n", blocks[0, 0])  # Example block


Shape of extracted blocks: (8, 8, 3, 3)
First 3x3 block:
 [[24 30 41]
 [92 45 37]
 [30 51 17]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [27]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)  

def symmetric_array(shape, fill_value=0, dtype=float):
    """Creates a symmetric 2D array"""
    assert shape[0] == shape[1], "Matrix must be square"
    data = np.full(shape, fill_value, dtype=dtype)
    return data.view(SymmetricArray)


Z = symmetric_array((5, 5))
Z[1, 3] = 7 
print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
import numpy as np

p, n = 4, 3 
M = np.random.rand(p, n, n)  
V = np.random.rand(p, n, 1) 

result = np.einsum('pij,pjk->ik', M, V)

print(result)  


[[3.70615473]
 [3.02216283]
 [3.00643426]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
import numpy as np


A = np.random.randint(0, 10, (16, 16))


block_size = 4
block_sum = A.reshape(16//block_size, block_size, 16//block_size, block_size).sum(axis=(1, 3))

print(block_sum)  


[[46 65 79 61]
 [78 66 73 74]
 [66 56 69 65]
 [99 91 73 57]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [32]:
import numpy as np
from scipy.signal import convolve2d

def game_of_life_step(grid):
    """Compute the next step in Conway's Game of Life."""
    
    # Define the 3x3 kernel for counting neighbors
    kernel = np.array([[1, 1, 1],
                       [1, 0, 1],  # Excludes center cell
                       [1, 1, 1]])
    
    # Count neighbors using 2D convolution
    neighbors = convolve2d(grid, kernel, mode='same', boundary='wrap')

    # Apply Game of Life rules
    new_grid = (neighbors == 3) | ((grid == 1) & (neighbors == 2))

    return new_grid.astype(int)

# Initialize a random 10x10 grid (1s = alive, 0s = dead)
np.random.seed(42)  # For reproducibility
grid = np.random.choice([0, 1], size=(10, 10), p=[0.7, 0.3])


for _ in range(5):  # Run for 5 iterations
    print(grid, "\n")
    grid = game_of_life_step(grid)


[[0 1 1 0 0 0 0 1 0 1]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 1]
 [1 0 0 1 1 1 1 0 0 0]
 [1 0 0 0 0 0 1 0 1 0]
 [0 1 1 0 1 0 0 0 0 0]] 

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 1 0 1 0]
 [1 0 1 0 0 0 1 1 0 1]
 [0 0 1 1 0 0 0 1 1 1]] 

[[1 0 0 1 0 0 0 0 1 1]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 0 0]
 [1 1 0 1 0 1 0 0 0 0]
 [1 1 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 1 1 1 1 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 1 1 0 1]] 

[[0 0 0 0 1 0 0 1 1 0]
 [1 1 0 1 1 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 0 0]
 [1 0 0 1 0 1 1 0 0 0]
 [0 0 1 1 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1]
 [0 1 1 1 0 0 0 1 0 0]] 

[[0 0 0 0 1 0 0 1 1 1]
 [1 0 1 1 1 0 0 0 1 1]
 [1 0 0 1 0 1 0 0 0 0]

#### 89. How to get the n largest values of an array (★★★)

In [33]:
import numpy as np

# Sample array
arr = np.array([10, 20, 5, 8, 70, 30, 100, 50])

# Number of largest elements to find
n = 3

# Get the n largest elements
largest_values = np.partition(arr, -n)[-n:]

print(largest_values)  # Output: [50 70 100]


[ 50  70 100]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [34]:
import numpy as np
from itertools import product

# Example vectors
vec1 = [1, 2]
vec2 = [3, 4]
vec3 = [5, 6]

# Compute the Cartesian product
cartesian_product = np.array(list(product(vec1, vec2, vec3)))

print(cartesian_product)


[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


#### 91. How to create a record array from a regular array? (★★★)

In [35]:
structured_array = np.array([(1, 'Alice', 25), 
                             (2, 'Bob', 30), 
                             (3, 'Charlie', 22)], 
                            dtype=[('ID', 'i4'), ('Name', 'U10'), ('Age', 'i4')])

print(structured_array)
print(structured_array['Name'])  # Access the 'Name' column


[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 22)]
['Alice' 'Bob' 'Charlie']


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [39]:
import time

Z = np.random.rand(10**6) 

start = time.time()
Z ** 3
print("Exponentiation (**):", time.time() - start)

start = time.time()
np.power(Z, 3)
print("np.power():", time.time() - start)

start = time.time()
Z * Z * Z
print("Multiplication (*):", time.time() - start)


Exponentiation (**): 0.03917646408081055
np.power(): 0.03482985496520996
Multiplication (*): 0.0050733089447021484


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [41]:
import numpy as np

# Sample data
A = np.random.randint(0, 10, (8, 3))  # 8 rows, 3 columns
B = np.random.randint(0, 10, (2, 2))  # 2 rows, 2 columns

# Function to find matching rows
def find_matching_rows(A, B):
    matches = []
    for row in B:
        mask = np.all(np.isin(A, row), axis=1)  # Corrected order of arguments
        matches.append(np.where(mask)[0])  # Extract matching row indices
    return matches

# Get matching row indices
matching_rows = find_matching_rows(A, B)

# Print results
print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nMatching rows in A for each row in B:", matching_rows)


Array A:
 [[2 2 6]
 [1 5 0]
 [8 7 5]
 [7 3 7]
 [0 5 0]
 [4 7 0]
 [1 5 4]
 [7 2 0]]

Array B:
 [[2 7]
 [4 5]]

Matching rows in A for each row in B: [array([], dtype=int64), array([], dtype=int64)]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [42]:
import numpy as np

# Sample data
A = np.random.randint(0, 10, (8, 3))  # 8 rows, 3 columns
B = np.random.randint(0, 10, (2, 2))  # 2 rows, 2 columns

# Function to find matching rows
def find_matching_rows(A, B):
    matches = []
    for row in B:
        mask = np.all(np.isin(A, row), axis=1)  # Corrected order of arguments
        matches.append(np.where(mask)[0])  # Extract matching row indices
    return matches

# Get matching row indices
matching_rows = find_matching_rows(A, B)

# Print results
print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nMatching rows in A for each row in B:", matching_rows)


Array A:
 [[7 6 4]
 [7 8 4]
 [1 5 1]
 [6 6 2]
 [3 0 2]
 [5 1 6]
 [4 5 5]
 [4 3 7]]

Array B:
 [[8 7]
 [7 3]]

Matching rows in A for each row in B: [array([], dtype=int64), array([], dtype=int64)]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [43]:
import numpy as np

vector = np.array([3, 7, 9, 15], dtype=np.uint8)

binary_matrix = np.array([list(np.binary_repr(x, width=8)) for x in vector], dtype=int)

print(binary_matrix)


[[0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

unique_rows = np.unique(array, axis=0)

print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [45]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

inner_product = np.einsum('i,i->', A, B)  

# Outer product
outer_product = np.einsum('i,j->ij', A, B) 

# Sum of all elements in A
sum_A = np.einsum('i->', A)  

# Element-wise multiplication
elementwise_mul = np.einsum('i,i->i', A, B)  

# Print results
print("Inner Product:", inner_product)
print("Outer Product:\n", outer_product)
print("Sum of A:", sum_A)
print("Element-wise Multiplication:", elementwise_mul)


Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of A: 6
Element-wise Multiplication: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [46]:
import numpy as np
from scipy.interpolate import interp1d


X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 0, 1, 0])

distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)  
arc_length = np.insert(np.cumsum(distances), 0, 0)  


num_samples = 10
new_arc_length = np.linspace(0, arc_length[-1], num_samples)

interp_x = interp1d(arc_length, X, kind='linear')
interp_y = interp1d(arc_length, Y, kind='linear')

new_X = interp_x(new_arc_length)
new_Y = interp_y(new_arc_length)

print("New X:", new_X)
print("New Y:", new_Y)


New X: [0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]
New Y: [0.         0.44444444 0.88888889 0.66666667 0.22222222 0.22222222
 0.66666667 0.88888889 0.44444444 0.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [47]:
import numpy as np

def select_multinomial_rows(n, X):
    # Condition 1: Check if all elements in a row are integers
    is_integer = np.all(np.mod(X, 1) == 0, axis=1)  
    
    # Condition 2: Check if row sums to n
    sums_to_n = np.sum(X, axis=1) == n  
    
    # Select valid rows
    return X[is_integer & sums_to_n]

# Example usage
X = np.array([[3, 2, 1], 
              [4.0, 1, 1], 
              [2, 2, 2], 
              [5, 0, 1], 
              [3.5, 1.5, 1]]) 

n = 6
valid_rows = select_multinomial_rows(n, X)

print(valid_rows)


[[3. 2. 1.]
 [4. 1. 1.]
 [2. 2. 2.]
 [5. 0. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [48]:
import numpy as np

def bootstrap_ci(X, N=1000, ci=95):
    means = np.array([np.mean(np.random.choice(X, size=len(X), replace=True)) for _ in range(N)])
    lower_percentile = (100 - ci) / 2
    upper_percentile = 100 - lower_percentile
    return np.percentile(means, [lower_percentile, upper_percentile])

# Example usage:
X = np.random.randn(100)  # Generate a random sample
ci_lower, ci_upper = bootstrap_ci(X)
print(f"95% Confidence Interval: ({ci_lower:.4f}, {ci_upper:.4f})")


95% Confidence Interval: (-0.2780, 0.1430)
