# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [2]:
import numpy as np
array = np.ones((3, 3), dtype=int)
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)



[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [8]:
print (0 * np.nan)
print (np.nan == np.nan)
print (np.inf > np.nan)
print (np.nan - np.nan)
print (np.nan in set([np.nan]))
print (0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [9]:
matrix = np.diag([1, 2, 3, 4], k=-1)
print (matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [10]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns

print (checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(index)


(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [12]:
checkerboard_base = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(checkerboard_base, (4, 4))

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [13]:
matrix = np.random.rand(5, 5)  
matrix_min = matrix.min()
matrix_max = matrix.max()
normalized_matrix = (matrix - matrix_min) / (matrix_max - matrix_min)

print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.02908159 0.90303667 0.3794066  0.93883731 0.17717689]
 [0.49631166 0.43117826 0.49579543 0.17365988 0.75385274]
 [0.24835748 0.34108325 0.31825946 0.41712243 0.30410774]
 [0.24880557 0.84836728 0.12723201 0.47460647 0.61947771]
 [0.44190279 0.96566732 0.89353595 0.63352803 0.77124987]]

Normalized Matrix:
 [[0.         0.93312876 0.37404479 0.97135338 0.15812252]
 [0.49886524 0.4293218  0.49831406 0.15436738 0.77384389]
 [0.2341226  0.33312665 0.30875751 0.41431428 0.2936476 ]
 [0.23460103 0.87475782 0.10479599 0.47569044 0.63037062]
 [0.44077246 1.         0.92298476 0.64537225 0.79241894]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [17]:
rgba_dtype = np.dtype([
    ('r', np.uint8),  # Red channel (0-255)
    ('g', np.uint8),  # Green channel (0-255)
    ('b', np.uint8),  # Blue channel (0-255)
    ('a', np.uint8)   # Alpha channel (0-255, transparency)
])

colors = np.array([
    (255, 0, 0, 255),   # Red
    (0, 255, 0, 255),   # Green
    (0, 0, 255, 255),   # Blue
    (255, 255, 0, 128)  # Yellow (semi-transparent)
], dtype=rgba_dtype)

print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 128)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [18]:
A = np.random.randint(1, 10, (5, 3))  

B = np.random.randint(1, 10, (3, 2))

C = np.dot(A, B)  # OR use C = A @ B

print("Matrix A (5x3):\n", A)
print("\nMatrix B (3x2):\n", B)
print("\nResulting Matrix C (5x2):\n", C)

Matrix A (5x3):
 [[4 7 4]
 [8 1 7]
 [2 8 9]
 [8 2 9]
 [3 7 7]]

Matrix B (3x2):
 [[4 4]
 [4 7]
 [1 5]]

Resulting Matrix C (5x2):
 [[ 48  85]
 [ 43  74]
 [ 49 109]
 [ 49  91]
 [ 47  96]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [19]:
arr = np.array([1, 3, 5, 7, 9, 2, 6, 8, 10])

arr[(arr > 3) & (arr < 8)] *= -1

print(arr)

[ 1  3 -5 -7  9  2 -6  8 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [20]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
import numpy as np
print(np.array(0) / np.array(0))  # Output: nan (with a warning)
print(np.array(0) // np.array(0))  # Raises ZeroDivisionError
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


C:\Users\User\AppData\Local\Temp\ipykernel_21044\2853037563.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))  # Output: nan (with a warning)
C:\Users\User\AppData\Local\Temp\ipykernel_21044\2853037563.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))  # Raises ZeroDivisionError
C:\Users\User\AppData\Local\Temp\ipykernel_21044\2853037563.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [25]:

Z = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7])

rounded_Z = np.copysign(np.ceil(np.abs(Z)), Z)
print(rounded_Z)


[-2. -2. -1.  1.  2.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [26]:


A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(A, B)
print(common_values)


[4 5]
