# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print (np.__version__)
np.show_config()

2.2.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
arr = np.zeros(10)
print("Memory size (in bytes):", arr.nbytes)


Memory size (in bytes): 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
null_vector = np.zeros(10)
null_vector[4] = 1
print (null_vector)



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
vect = np.arange(10, 50)
print (vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
vector = np.arange(10,50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
ran_int_array = np.random.randint(0, 100, (3, 3, 3))

print (ran_int_array)


[[[ 6 82 61]
  [78 64 62]
  [14 39 14]]

 [[73 79 21]
  [80 87 63]
  [27 15 60]]

 [[79 25 91]
  [49 25 95]
  [77 80 42]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
random_array = np.random.randint(0, 100, (10, 10))


min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Integer Array:\n", random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random 10x10 Integer Array:
 [[65 88 70 48  7 79 25 20 89 29]
 [73 59 49 89  6 35  2 22 46 45]
 [51 92 56 83 78 27  4  1 63 52]
 [79 32  2 47  8 10 82 48 40 29]
 [39 15 86 94 36 95 66 74 30 65]
 [68 26 72 38 87 98 15 67 65 88]
 [86 37 78 84 65 46 26  2 99 59]
 [96 73 88 21 10 85 44 87 92 73]
 [44 14  9 42 10  8 30 79 33 99]
 [89 90 98 62 98 53 56 31 43 60]]

Minimum Value: 1
Maximum Value: 99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
random_vector = np.random.randint(0, 100, 30)

mean_value = np.mean(random_vector)

print("Random Vector:\n", random_vector)
print("\nMean Value:", mean_value)

Random Vector:
 [18 71  0 84 57 75 24 96  4 65 18 26 74 34 75 45 35 95 66 60 70 78 13 87
 58 58 88 82 17 83]

Mean Value: 55.2


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
rows, cols = 5, 5

array = np.zeros((rows, cols), dtype=int)

array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
